### ISSUE TITLE
Unable to switch from Razorpay to Stripe

### ISSUE THREAD

**Issue by Hemann55** [SGFGOV/medusa-payment-razorpay#2]
I using Stripe and Razorpay but not able to switch from Razorpay to Stripe at checkout using setPaymentSession as described here -
https://docs.medusajs.com/api/store#tag/Cart/operation/PostCartsCartPaymentSession

Setting cart.payment_session from Stripe to Razorpay works fine but Razorpay to Stripe throws the following error -

![terminal](https://user-images.githubusercontent.com/74895639/225726758-d6ec747b-7659-4cb0-ab17-a4635cd47003.png)
![devtools](https://user-images.githubusercontent.com/74895639/225726764-5d88f1f6-7e00-466f-b798-a0b33ef791de.png)

Any idea what's causing this issue?

**Comment by SGFGOV** [comment]
Hi

Thanks for reporting this..will investigate and get back.

Best regards 
Govind

**Comment by SGFGOV** [comment]
would you mind testing medusa-payment-razorpay@3.0.2-alpha-2.

**Comment by SGFGOV** [comment]
Hi,

The reason the delete fails is because, razorpay doesn't support cancellations. Thus I didn't really bother about it :).. my bad. for some reason the "3.0.2-alpha-2" didn't have the fix..  I suspect a build issue. If its not too much trouble can you try "3.0.2-alpha-5"  and share a screen shot if it fails. Alternatively you can submit a PR and I'll be happy to merge it in

**Comment by Hemann55** [comment]
Since Razorpay does not support cancelling/deleting orders or payments, I kept the deletePayment function in services directory empty. This resolves the above error. 

```
async deletePayment(payment) {
//empty
}
```
